# 1. Numpy and Linear Algebra (선형대수)

- 수치 data 를 다루는데 효율적이고 높은 성능 제공

- 각종 수학적 함수 제공

- Python scientific library 들이 Numpy 기반으로 구축

### ndarray

- n-dimensional array (다차원 배열 객체) 로 구성 

In [1]:
import sys
import numpy as np

In [2]:
# 스칼라
x = 6
x

6

In [3]:
a = np.array([1])
a, a.shape

(array([1]), (1,))

In [4]:
# 벡터
x = np.array([1,2,3])

print("x = ", x)
print("dimension of x is {}".format(x.shape))

x =  [1 2 3]
dimension of x is (3,)


In [5]:
np.argmax(x)

2

In [6]:
# matrix
y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("array dimension {}".format(y.shape))
print("array size {}".format(y.size))
print("argmax {}".format(np.argmax(y, axis=1)))

array dimension (3, 3)
array size 9
argmax [2 2 2]


In [5]:
z = np.array([[[1, 2, 3], 
               [3, 2, 5]], 
              [[1, 7, 8], 
               [5, 4, 6]]])

z, z.shape

(array([[[1, 2, 3],
         [3, 2, 5]],
 
        [[1, 7, 8],
         [5, 4, 6]]]),
 (2, 2, 3))

## Indexing / Slicing

<img src="axes.png" width="600">

<img src="numpy.png" width="400">



<img src="tensor.jpg" width="600">

## Slicing

<img src="numpy1.png" width="300">

In [9]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(arr[:2, 1:])

[[2 3]
 [5 6]]


In [11]:
arr[2]

array([7, 8, 9])

In [12]:
arr[2, :]

array([7, 8, 9])

In [13]:
arr[2:, :]

array([[7, 8, 9]])

In [14]:
print(arr[:, :2])

[[1 2]
 [4 5]
 [7 8]]


In [15]:
arr[1, :2]

array([4, 5])

In [16]:
arr[1:2, :2]

array([[4, 5]])

### 벡터의 내적(inner product) 
- 내적이 되려면 두 벡터의 dimension 이 같아야 한다. 내적은 각 element 의 곱을 모두 더한 것이다.
- inner product 은 dot product (점곱) 이라고도 불린다.

In [17]:
a = np.array([2,5,1])
print(a)

[2 5 1]


In [18]:
b = np.array([4,3,5])
print(b)

[4 3 5]


$\mathbf{a}\mathbf{b}^T = \begin{bmatrix} 2 & 5 & 1\end{bmatrix}\begin{bmatrix}4\\3\\5\end{bmatrix} = \begin{bmatrix}2*4 + 5*3 + 1*5\end{bmatrix} = 28$

In [19]:
# a, b 의 내적 ==> scalar 
np.dot(a, b.T)

28

## matrix 곱셈 (행렬 곱셈, dot product)

### 두 행렬 A 와 B 는 A 의 열(column) 갯수가 B 의 행(row) 갯수와 같을 때 곱할 수 있다. 결과 행렬 C 의 shape 은 A 의 row x B 의 column 이 된다.

<img src="matmul2.png" width="250">
<img src="matmul.png" width="350">

$$\mathbf{A} = \begin{bmatrix}2&5&1\\4&5&3\end{bmatrix} \text{ and } \mathbf{B}=\begin{bmatrix}4&3&5&7\\9&5&3&4\\5&3&6&7\end{bmatrix}$$
$$\mathbf{AB} = \begin{bmatrix}2*4+5*9+1*5&2*3+5*5+1*3&2*5+5*3+1*6&2*7+5*4+1*7\\4*4+5*9+3*5&4*3+5*5+3*3&4*5+5*3+3*6&4*7+5*4+3*7\end{bmatrix}$$

In [20]:
a = np.array([[2, 1], [1, 4]])
b = np.array([[1, 2, 0], [0, 1, 2]])
print(a)
print()
print(b)
print()
print(np.matmul(a, b))

[[2 1]
 [1 4]]

[[1 2 0]
 [0 1 2]]

[[2 5 2]
 [1 6 8]]


### 전치행렬 (Transposed Matrix)

In [1]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
A = np.arange(9)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
B = A.reshape(3, 3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
B.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [7]:
np.transpose(B)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [8]:
B.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])