# Simple LSTM

## 1) data 는 0 ~ 99 까지의 연속된 숫자이고, target 은 (1 ~ 101) * 2 으로 구성한다. 입력  data 에 대응하는 출력 data 를 예측하는 model 을 LSTM 으로 작성

## 연속된 5 개의 숫자를 보고 다음 숫자를 알아맞추도록 LSTM 을 이용한 model 작성

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

### Training Data 작성 요령

In [2]:
numbers = [[i] for i in range(105)]
numbers[:5]

[[0], [1], [2], [3], [4]]

In [3]:
data = []
target = []
for i in range(5, len(numbers)):
    data.append(numbers[i-5: i])
    target.append(numbers[i][0] * 2)

print(data[5])
print(target[5])

[[5], [6], [7], [8], [9]]
20


In [4]:
# List --> numpy ndarray 변환
data = np.array(data, dtype="float32")
target = np.array(target, dtype="float32")

# Normalize
data = data / 100.
target = target / 100.

In [5]:
data.shape, target.shape

((100, 5, 1), (100,))

In [6]:
model = Sequential()
model.add(LSTM(16, input_shape=(5, 1)))
model.add(Dense(1))

In [7]:
model.compile(optimizer='adam', loss='mae', metrics=['mae'])

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 16)                1152      
                                                                 
 dense (Dense)               (None, 1)                 17        
                                                                 
Total params: 1,169
Trainable params: 1,169
Non-trainable params: 0
_________________________________________________________________


In [9]:
history = model.fit(data, target, epochs=500, validation_split=0.2)

Epoch 1/500
3/3 [==============================] - 2s 169ms/step - loss: 1.0071 - mae: 1.0071 - val_loss: 2.1093 - val_mae: 2.1093
Epoch 2/500
3/3 [==============================] - 0s 12ms/step - loss: 0.9839 - mae: 0.9839 - val_loss: 2.0747 - val_mae: 2.0747
Epoch 3/500
3/3 [==============================] - 0s 12ms/step - loss: 0.9613 - mae: 0.9613 - val_loss: 2.0416 - val_mae: 2.0416
Epoch 4/500
3/3 [==============================] - 0s 13ms/step - loss: 0.9395 - mae: 0.9395 - val_loss: 2.0097 - val_mae: 2.0097
Epoch 5/500
3/3 [==============================] - 0s 11ms/step - loss: 0.9188 - mae: 0.9188 - val_loss: 1.9790 - val_mae: 1.9790
Epoch 6/500
3/3 [==============================] - 0s 12ms/step - loss: 0.8985 - mae: 0.8985 - val_loss: 1.9495 - val_mae: 1.9495
Epoch 7/500
3/3 [==============================] - 0s 11ms/step - loss: 0.8789 - mae: 0.8789 - val_loss: 1.9209 - val_mae: 1.9209
Epoch 8/500
3/3 [==============================] - 0s 12ms/step - loss: 0.8597 - mae: 0.8

3/3 [==============================] - 0s 13ms/step - loss: 0.0269 - mae: 0.0269 - val_loss: 0.0146 - val_mae: 0.0146
Epoch 64/500
3/3 [==============================] - 0s 11ms/step - loss: 0.0268 - mae: 0.0268 - val_loss: 0.0190 - val_mae: 0.0190
Epoch 65/500
3/3 [==============================] - 0s 11ms/step - loss: 0.0255 - mae: 0.0255 - val_loss: 0.0201 - val_mae: 0.0201
Epoch 66/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0246 - mae: 0.0246 - val_loss: 0.0112 - val_mae: 0.0112
Epoch 67/500
3/3 [==============================] - 0s 13ms/step - loss: 0.0232 - mae: 0.0232 - val_loss: 0.0230 - val_mae: 0.0230
Epoch 68/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0214 - mae: 0.0214 - val_loss: 0.0140 - val_mae: 0.0140
Epoch 69/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0232 - mae: 0.0232 - val_loss: 0.0266 - val_mae: 0.0266
Epoch 70/500
3/3 [==============================] - 0s 13ms/step - loss: 0.0236 - mae: 0.0236 - 

3/3 [==============================] - 0s 11ms/step - loss: 0.0112 - mae: 0.0112 - val_loss: 0.0822 - val_mae: 0.0822
Epoch 126/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0775 - val_mae: 0.0775
Epoch 127/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0113 - mae: 0.0113 - val_loss: 0.0721 - val_mae: 0.0721
Epoch 128/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0115 - mae: 0.0115 - val_loss: 0.0847 - val_mae: 0.0847
Epoch 129/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0121 - mae: 0.0121 - val_loss: 0.0812 - val_mae: 0.0812
Epoch 130/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0112 - mae: 0.0112 - val_loss: 0.0741 - val_mae: 0.0741
Epoch 131/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0111 - mae: 0.0111 - val_loss: 0.0862 - val_mae: 0.0862
Epoch 132/500
3/3 [==============================] - 0s 11ms/step - loss: 0.0123 - mae: 0.

3/3 [==============================] - 0s 15ms/step - loss: 0.0102 - mae: 0.0102 - val_loss: 0.0779 - val_mae: 0.0779
Epoch 188/500
3/3 [==============================] - 0s 15ms/step - loss: 0.0099 - mae: 0.0099 - val_loss: 0.0833 - val_mae: 0.0833
Epoch 189/500
3/3 [==============================] - 0s 14ms/step - loss: 0.0102 - mae: 0.0102 - val_loss: 0.0783 - val_mae: 0.0783
Epoch 190/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0100 - mae: 0.0100 - val_loss: 0.0775 - val_mae: 0.0775
Epoch 191/500
3/3 [==============================] - 0s 13ms/step - loss: 0.0102 - mae: 0.0102 - val_loss: 0.0785 - val_mae: 0.0785
Epoch 192/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0103 - mae: 0.0103 - val_loss: 0.0806 - val_mae: 0.0806
Epoch 193/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0100 - mae: 0.0100 - val_loss: 0.0710 - val_mae: 0.0710
Epoch 194/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0100 - mae: 0.

3/3 [==============================] - 0s 12ms/step - loss: 0.0086 - mae: 0.0086 - val_loss: 0.0734 - val_mae: 0.0734
Epoch 250/500
3/3 [==============================] - 0s 15ms/step - loss: 0.0086 - mae: 0.0086 - val_loss: 0.0704 - val_mae: 0.0704
Epoch 251/500
3/3 [==============================] - 0s 15ms/step - loss: 0.0088 - mae: 0.0088 - val_loss: 0.0723 - val_mae: 0.0723
Epoch 252/500
3/3 [==============================] - 0s 15ms/step - loss: 0.0086 - mae: 0.0086 - val_loss: 0.0770 - val_mae: 0.0770
Epoch 253/500
3/3 [==============================] - 0s 15ms/step - loss: 0.0089 - mae: 0.0089 - val_loss: 0.0718 - val_mae: 0.0718
Epoch 254/500
3/3 [==============================] - 0s 13ms/step - loss: 0.0085 - mae: 0.0085 - val_loss: 0.0689 - val_mae: 0.0689
Epoch 255/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0085 - mae: 0.0085 - val_loss: 0.0657 - val_mae: 0.0657
Epoch 256/500
3/3 [==============================] - 0s 13ms/step - loss: 0.0086 - mae: 0.

3/3 [==============================] - 0s 12ms/step - loss: 0.0080 - mae: 0.0080 - val_loss: 0.0605 - val_mae: 0.0605
Epoch 312/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0073 - mae: 0.0073 - val_loss: 0.0689 - val_mae: 0.0689
Epoch 313/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0080 - mae: 0.0080 - val_loss: 0.0550 - val_mae: 0.0550
Epoch 314/500
3/3 [==============================] - 0s 14ms/step - loss: 0.0086 - mae: 0.0086 - val_loss: 0.0572 - val_mae: 0.0572
Epoch 315/500
3/3 [==============================] - 0s 17ms/step - loss: 0.0078 - mae: 0.0078 - val_loss: 0.0627 - val_mae: 0.0627
Epoch 316/500
3/3 [==============================] - 0s 18ms/step - loss: 0.0079 - mae: 0.0079 - val_loss: 0.0505 - val_mae: 0.0505
Epoch 317/500
3/3 [==============================] - 0s 19ms/step - loss: 0.0082 - mae: 0.0082 - val_loss: 0.0729 - val_mae: 0.0729
Epoch 318/500
3/3 [==============================] - 0s 19ms/step - loss: 0.0086 - mae: 0.

3/3 [==============================] - 0s 11ms/step - loss: 0.0083 - mae: 0.0083 - val_loss: 0.0519 - val_mae: 0.0519
Epoch 374/500
3/3 [==============================] - 0s 13ms/step - loss: 0.0068 - mae: 0.0068 - val_loss: 0.0641 - val_mae: 0.0641
Epoch 375/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0066 - mae: 0.0066 - val_loss: 0.0461 - val_mae: 0.0461
Epoch 376/500
3/3 [==============================] - 0s 13ms/step - loss: 0.0070 - mae: 0.0070 - val_loss: 0.0636 - val_mae: 0.0636
Epoch 377/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0079 - mae: 0.0079 - val_loss: 0.0494 - val_mae: 0.0494
Epoch 378/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0066 - mae: 0.0066 - val_loss: 0.0575 - val_mae: 0.0575
Epoch 379/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0066 - mae: 0.0066 - val_loss: 0.0563 - val_mae: 0.0563
Epoch 380/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0064 - mae: 0.

3/3 [==============================] - 0s 12ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0382 - val_mae: 0.0382
Epoch 436/500
3/3 [==============================] - 0s 11ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0539 - val_mae: 0.0539
Epoch 437/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0063 - mae: 0.0063 - val_loss: 0.0424 - val_mae: 0.0424
Epoch 438/500
3/3 [==============================] - 0s 13ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0471 - val_mae: 0.0471
Epoch 439/500
3/3 [==============================] - 0s 14ms/step - loss: 0.0053 - mae: 0.0053 - val_loss: 0.0470 - val_mae: 0.0470
Epoch 440/500
3/3 [==============================] - 0s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0496 - val_mae: 0.0496
Epoch 441/500
3/3 [==============================] - 0s 14ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0448 - val_mae: 0.0448
Epoch 442/500
3/3 [==============================] - 0s 12ms/step - loss: 0.0055 - mae: 0.

3/3 [==============================] - 0s 15ms/step - loss: 0.0048 - mae: 0.0048 - val_loss: 0.0515 - val_mae: 0.0515
Epoch 498/500
3/3 [==============================] - 0s 14ms/step - loss: 0.0069 - mae: 0.0069 - val_loss: 0.0279 - val_mae: 0.0279
Epoch 499/500
3/3 [==============================] - 0s 17ms/step - loss: 0.0068 - mae: 0.0068 - val_loss: 0.0449 - val_mae: 0.0449
Epoch 500/500
3/3 [==============================] - 0s 16ms/step - loss: 0.0064 - mae: 0.0064 - val_loss: 0.0348 - val_mae: 0.0348


In [10]:
test_data = [[35], [36], [37], [38], [39]]

x = np.array(test_data, dtype="float32") / 100.

model.predict(x.reshape(1, 5, 1)) * 100

1/1 [==============================] - 0s 401ms/step


array([[80.07275]], dtype=float32)

In [11]:
test_data = [[5], [6], [7], [8], [9]]

x = np.array(test_data, dtype="float32") / 100.

model.predict(x.reshape(1, 5, 1)) * 100

1/1 [==============================] - 0s 23ms/step


array([[20.647942]], dtype=float32)

In [12]:
test_data = [[60], [61], [62], [63], [64]]

x = np.array(test_data, dtype="float32") / 100.

model.predict(x.reshape(1, 5, 1)) * 100

1/1 [==============================] - 0s 18ms/step


array([[130.81592]], dtype=float32)